[theme]
primaryColor = "#1E90FF"  # צבע עיקרי לכפתורים ורכיבים חשובים
backgroundColor = "#F0F2F6"  # צבע רקע לאפליקציה
secondaryBackgroundColor = "#FFFFFF"  # צבע רקע משני לאזורים פנימיים
textColor = "#000000"  # צבע הטקסט הכללי
font = "sans serif"  # פונטים פשוטים ונקיים

 [layout]
wide = true
